version: '3'
services:
  app:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3389:3389
    shm_size: '1gb'